[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules"]
test = 'test'
cache_path  = 'cache_forge'
solc_version = "0.8.20"                                   
evm_version = "shanghai"                                     
optimizer = true                                          
optimizer_runs = 10_000_000                               
via_ir = false                                            
bytecode_hash = "none"                                    